### ISSUE TITLE
A notice

### ISSUE THREAD

**Issue by psprint** [00dani/dot-zsh#1]
Hello,
I'm browsing Github to find properly licensed and interesting `.zshrc`s containing Zplugin invocations, for https://github.com/zdharma/zplugin-configs repository. Could I add your `zplugin` file? It is nice and shows users that the ice mods can use the colon as a separator or how to automatically install Zplugin. If you would agree, could I ask you to create an issue in the repo, using following link: https://github.com/zdharma/zplugin-configs/issues/new?template=request-to-add-zshrc-to-the-zplugin-configs-repo.md? You can paste the file there.

One thing – the notice from the title – the `trapd00r/LS_COLORS` invocation can now use the `nocompile'!'` ice to properly compile the file pointed to by the `pick:c.zsh` ice-mod.

**Comment by 00dani** [comment]
Yes, absolutely! I'll check out the new `nocompile'!'` ice, tidy things up a bit, and make a PR shortly. 🐱
